[package]
name = "spec_an_calibrator"
version = "0.1.0"
authors = ["oebee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
