[package]
name = "spec_an_calibrator"
version = "0.1.0"
authors = ["larrym"]
edition = "2018"

[dependencies]
crossterm = "0.17"
tui = {version = "0.12", default-features = false, features = ['crossterm']}
